name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.0.x

      - name: Install dependencies
        run: cd /git/Front-End-Rojo/; npm i
      - name: build
        run: cd /git/Front-End-Rojo/; npm run build
      - name: implement
        run: rm -rf /var/www/webappFront/build/
      - name: mv directory
        run: mv /git/Front-End-Rojo/build /var/www/webappFront
      - name: restart nginx
        run: systemctl restart nginx; systemctl status nginx
