name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
      
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Use Node.js 16.x

      - name: Install dependencies
        run: cd /projetorojo/rojo_app; npm ci
      - run: npm run build --if-present
      - run: mv build/ /var/www/webappFront
